In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
class Model:
    
    def __init__(self):
        pass
    
    def fit(self,X,y):
        pass
    
    def predict(self,X):
        pass
    
    def score(self,X,y):
        pass
    
    
        


class NaiveBayes(Model):
    
    def __init__(self):
        self.is_fitted=False
        
    def fit(self,X,y,likelihood='gauusian',)
    
    

In [2]:
from keras.datasets import cifar10
X_train,y_train,X_test,y_test = cifar10.load_data()

Exception: URL fetch failure on https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz: None -- [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)

In [4]:
a = np.array([1,2,3])
a.nunique()

AttributeError: 'numpy.ndarray' object has no attribute 'nunique'

In [5]:
np.unique(a)

array([1, 2, 3])

In [163]:
X = np.array([[0,0,1],[0,1,1],[0,1,1],[1,1,0],[0,1,0],[0,1,1],[1,0,0],[1,1,0],[1,0,1],[1,0,0]])
X

array([[0, 0, 1],
       [0, 1, 1],
       [0, 1, 1],
       [1, 1, 0],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 1, 0],
       [1, 0, 1],
       [1, 0, 0]])

In [168]:
X[6:]

array([[1, 0, 0],
       [1, 1, 0],
       [1, 0, 1],
       [1, 0, 0]])

In [170]:
np.var(X[6:],axis=0)

array([0.    , 0.1875, 0.1875])

In [190]:
y = np.array([1,1,1,1,1,1,0,0,0,0])
y

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [9]:
for a in np.zeros(12):

(12,)

In [21]:

def encode_onehot(y):
    """return a dense matrix of y encoded in onehot scheme

    Args:
        y (np.array): vector to be encoded
    """

    classes = np.unique(y)
    class_mapping = {k: v for v, k in enumerate(classes)}
    Y = np.zeros((y.shape[0], len(classes)))
    for i in range(y.shape[0]):
        Y[i][class_mapping[y[i]]] = 1
    return Y, classes, class_mapping

In [22]:
Y,c,cm = encode_onehot(y)

In [23]:
Y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [35]:
fl = Y.T@X
ft = np.sum(fl,axis=1)

In [36]:
fl,ft

(array([[4., 1., 1.],
        [1., 5., 4.]]),
 array([ 6., 10.]))

In [43]:
fl + 0.001

array([[4.001, 1.001, 1.001],
       [1.001, 5.001, 4.001]])

In [41]:
np.divide(fl,ft.reshape(2,1))

array([[0.66666667, 0.16666667, 0.16666667],
       [0.1       , 0.5       , 0.4       ]])

In [45]:
ft.reshape(2,1) 

array([[10.],
       [14.]])

In [48]:
mu = np.mean(X,axis=0)
var = np.var(X,axis=0)

In [49]:
mu
var

array([0.25, 0.24, 0.25])

In [51]:
np.log(mu)

array([-0.69314718, -0.51082562, -0.69314718])

In [149]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


def encode_onehot(y):
    """return a dense matrix of y encoded in onehot scheme

    Args:
        y (np.array): vector to be encoded
    """

    classes = np.unique(y)
    class_mapping = {k: v for v, k in enumerate(classes)}
    Y = np.zeros((y.shape[0], len(classes)))
    for i in range(y.shape[0]):
        Y[i][class_mapping[y[i]]] = 1
    return Y, classes, class_mapping


class Model:
    def __init__(self):
        pass

    def fit(self, X, y):
        pass

    def predict(self, X):
        pass

    def score(self, X, y):
        pass


class NaiveBayes(Model):
    def __init__(self):
        self.is_fitted = False
        self.classes = None  # from N to classes
        self.feature_likelihood = None
        self.number_of_features = None
        self.class_mapping = {}  # from give classes to N
        self.parameters = {}

    def __initialize(self, X, y):
        Y, self.classes, self.class_mapping = encode_onehot(y)
        return Y

    def fit(self, X, y, likelihood="gauusian", priors=None, **kwargs):
        """fit Naive bayes model with given data and specified parameters

        Args:
            X (np.array): training data in the format of number_of_examples X number_of_features
            y (np.array): training label
            likelihood (str, optional): distribution family of likelihood function. Defaults to 'gauusian'. supported types
            gauusian, multinomial, custom in case of custom a likelihood_fit function should be passed as keyword argument
            priors (np.array, optional): specify the prior distribution of classes. it should be the same size of number of
            classes and it should sum to one. Defaults to None.
            alpha (float, kwargs): smoothing used in multinomial NB
        """
        Y = self.__initialize(X, y)
        self.number_of_features = X.shape[1]
        self.likelihood = likelihood
        self.priors = (
            priors
            if priors is not None
            else np.ones(len(self.classes)) / len(self.classes)
        )

        if likelihood == "gauusian":
            mus = np.mean(X, axis=0)
            variances = np.var(X, axis=0)
            self.parameters["mu"] = mus
            self.parameters["variance"] = variances

        if likelihood == "multinomial":
            alpha = kwargs.get("alpha", 0.000000001)
            assert alpha > 0

            feature_likelihood = (Y.T @ X) + alpha
            total_class_count = (
                np.sum(feature_likelihood, axis=1).reshape(len(self.classes, 1))
                + self.number_of_features * alpha
            )
            feature_likelihood = np.divide(feature_likelihood, total_class_count)

            self.parameters["alpha"] = alpha
            self.parameters["featureLikelihood"] = self.feature_likelihood
            # NOTE: summing over feature value hence values must be indicative of importance not perpendicular values like categories in that case first make it one-hot

        self.is_fitted = True

    def score(self, X, y):
        """compute MSE score by default

        Args:
            X (np.array): features
            y (np.array): labels
        """
        pass

    def predict(self, X):
        """predict using fitted model and it should be called after fit

        Args:
            X (np.array): features

        Returns:
            [np.array]: predicted classes
        """

        assert self.is_fitted
        log_priors = np.log(self.priors)
        if self.likelihood == "gauusian":
            mu = self.parameters["mu"]
            var = self.parameters["variance"]
            log_likelihood = [
                0
                + -0.5
                * (
                    np.sum(np.log(2 * np.pi * var[i]))
                    + np.sum(((X - mu[i]) ** 2) / var[i],axis=1)
                )
                for i in range(len(self.classes))
            ]

        return np.array(log_likelihood).T


In [57]:
nb = NaiveBayes()

nb.fit(X,y)

In [58]:
ar = nb.predict(X)

IndexError: too many indices for array

In [59]:
nb.parameters

{'mu': array([0.5, 0.6, 0.5]), 'variance': array([0.25, 0.24, 0.25])}

In [98]:
log_priors = np.log(nb.priors)
mu = nb.parameters["mu"]
var = nb.parameters["variance"]

In [119]:
np.sum(((X - mu[0]) ** 2) / var[0],axis=1).shape

(150,)

In [208]:
s = Y.T@X
mu=s/np.sum(Y,axis=0).reshape(2,1)

In [213]:
v=(X - Y@mu)**2


In [220]:
vs = Y.T@v
vs/(np.sum(Y,axis=0)).reshape(2,1)

array([[0.        , 0.1875    , 0.1875    ],
       [0.13888889, 0.13888889, 0.22222222]])

In [219]:
np.var(X[:6],axis=0)

array([0.13888889, 0.13888889, 0.22222222])

In [108]:
log_likelihood = [
                log_priors[i]
                + -0.5
                * (
                    np.sum(np.log(2 * np.pi * var[i]))
                    + np.sum(((X - mu[i]) ** 2) / var[i])
                )
                for i in range(len(nb.classes))
            ]

In [100]:
log_likelihood

[array([-31.17049488, -30.73080084, -31.66597805, -29.84763045,
        -31.41729089, -27.09032332, -29.47601807, -30.11144687,
        -30.80171923, -31.40121605, -30.8518349 , -29.29919488,
        -32.28438644, -35.19771403, -34.82326492, -31.48442696,
        -30.44523611, -29.66986168, -28.13235091, -29.70390251,
        -28.53989528, -27.9035209 , -35.40763248, -24.05596167,
        -27.18015329, -29.05334445, -26.35088088, -30.30529048,
        -30.97665127, -29.07036486, -29.03537845, -27.16313287,
        -34.13393813, -34.01006734, -31.40121605, -32.63708725,
        -32.08865167, -31.40121605, -31.64895764, -30.11144687,
        -30.58801847, -31.75675359, -31.66597805, -23.80822009,
        -25.32492812, -29.23016764, -30.39228371, -30.74782125,
        -30.8518349 , -30.83576006, -15.6422035 , -13.17140668,
        -16.55941472, -13.45886257, -14.12549547, -15.13253665,
        -14.05268592, -14.04417571, -15.78498587, -10.84528339,
        -16.25115611, -11.14314064, -16.

In [67]:
var

array([0.25, 0.24, 0.25])

In [75]:
df = pd.read_csv('../Data/iris.data',header=None,names=['x0','x1','x2','x3','label'])
df.head()

x0   x1   x2   x3        label
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [81]:
X,y = df[['x1','x2','x3']].values , df['label'].values

In [86]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [87]:
y_train.shape

(112,)

In [95]:
nb.classes

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [155]:
nb = NaiveBayes()

nb.fit(X_train,y_train)

In [151]:
a = nb.predict(X_test)

In [152]:
a

array([[-18.51691239,  -2.91935567, -13.1622992 ],
       [-19.62323932,  -2.60559878, -18.96649426],
       [-29.75322261,  -4.28081844,  -6.59457765],
       [-11.42790981,  -2.94171883,  -4.61019279],
       [-16.61062598,  -2.80636283, -12.57691438],
       [-14.03392436,  -2.674706  , -11.48207634],
       [-30.30260376,  -4.46090077,  -4.63821344],
       [-11.26337914,  -2.55263338, -10.0241313 ],
       [-12.05577398,  -2.47315727, -12.08894851],
       [-38.13199437,  -3.23905365, -31.32897386],
       [-27.93676616,  -4.27852047,  -4.5188716 ],
       [-14.68637358,  -2.67123102, -12.2895938 ],
       [-14.10578833,  -2.76326189, -10.28981935],
       [-28.57124939,  -4.25290652,  -5.6244533 ],
       [-28.37740578,  -4.26249073,  -5.2613463 ],
       [-33.66791791,  -3.07982118, -28.44023333],
       [-14.89534645,  -2.49395109, -15.08599685],
       [-12.14182163,  -2.33073922, -14.24044099],
       [-30.3186786 ,  -4.35648328,  -6.16105606],
       [-24.97426849,  -3.11244

In [187]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
# gnb.fit(X_train,y_train)

In [192]:
gnb.fit(X,y)

GaussianNB()

In [194]:
y

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [193]:
gnb.predict(np.array([[1,1,0],[1,1,1]]))

array([0, 0])

In [161]:
nb.parameters['variance']

array([0.18884885, 3.18604273, 0.61498007])

In [160]:
gnb.var_

AttributeError: 'GaussianNB' object has no attribute 'var_'

In [158]:
gnb.theta_.shape

(3, 3)

In [182]:
0.222 * 0.00001

2.2200000000000003e-06

In [171]:
import math
def normpdf(x, mean, var):
    denom = (2*math.pi*var)**.5
    num = math.exp(-(float(x)-float(mean))**2/(2*var))
    return num/denom

In [186]:
normpdf(1,0.25,0.187)

0.20502447897710813