In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
class Model:
    
    def __init__(self):
        pass
    
    def fit(self,X,y):
        pass
    
    def predict(self,X):
        pass
    
    def score(self,X,y):
        pass
    
    
        


class NaiveBayes(Model):
    
    def __init__(self):
        self.is_fitted=False
        
    def fit(self,X,y,likelihood='gauusian',)
    
    

In [2]:
from keras.datasets import cifar10
X_train,y_train,X_test,y_test = cifar10.load_data()

Exception: URL fetch failure on https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz: None -- [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)

In [4]:
a = np.array([1,2,3])
a.nunique()

AttributeError: 'numpy.ndarray' object has no attribute 'nunique'

In [5]:
np.unique(a)

array([1, 2, 3])

In [6]:
X = np.array([[0,0,1],[0,1,1],[0,1,1],[1,1,0],[0,1,0],[0,1,1],[1,0,0],[1,1,0],[1,0,1],[1,0,0]])
X

array([[0, 0, 1],
       [0, 1, 1],
       [0, 1, 1],
       [1, 1, 0],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 1, 0],
       [1, 0, 1],
       [1, 0, 0]])

In [7]:
y = np.array([1,1,1,1,1,1,0,0,0,0])
y

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [9]:
for a in np.zeros(12):

(12,)

In [19]:

def encode_onehot(y):
    """return a dense matrix of y encoded in onehot scheme

    Args:
        y (np.array): vector to be encoded
    """

    classes = np.unique(y)
    class_mapping = {k: v for v, k in enumerate(classes)}
    Y = np.zeros((y.shape[0], len(classes)))
    for i in range(y.shape[0]):
        Y[i][class_mapping[y[i]]] = 1
    return Y, classes, class_mapping

In [20]:
Y,c,cm = encode_onehot(y)

0
1
2
3
4
5
6
7
8
9


In [15]:
Y

array([[1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
c

array([0, 1])

In [18]:
cm

{0: 0, 1: 1}